export interface NutritionData {
  name: string;
  calories: number;       // Kalori (kkal)
  carbohydrates: number;  // Karbohidrat (g)
  protein: number;        // Protein (g)
  fat: number;            // Lemak (g)
  fiber: number;          // Serat (g)
  sugar: number;          // Gula (g)
  sodium: number;         // Natrium (mg)
}

export const nutritionData: NutritionData[] = [
  {
    name: "Ayam (daging tanpa kulit, matang)",
    calories: 165,
    carbohydrates: 0,
    protein: 31,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
  },
  {
    name: "Telur ayam (rebus)",
    calories: 155,
    carbohydrates: 1.1,
    protein: 13,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
  },
  {
    name: "Bayam (mentah)",
    calories: 23,
    carbohydrates: 3.6,
    protein: 2.9,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
  },
  {
    name: "Sawi hijau (mentah)",
    calories: 20,
    carbohydrates: 3.1,
    protein: 2.7,
    fat: 0.2,
    fiber: 1.6,
    sugar: 1.2,
    sodium: 14,
  },
  {
    name: "Kangkung (mentah)",
    calories: 19,
    carbohydrates: 3.1,
    protein: 2.6,
    fat: 0.2,
    fiber: 2.1,
    sugar: 0.5,
    sodium: 50,
  },
  {
    name: "Nasi putih (matang)",
    calories: 130,
    carbohydrates: 28,
    protein: 2.7,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
  },
  {
    name: "Daging sapi (tanpa lemak, matang)",
    calories: 250,
    carbohydrates: 0,
    protein: 26,
    fat: 17,
    fiber: 0,
    sugar: 0,
    sodium: 72,
  },
  {
    name: "Daging kambing (tanpa lemak, matang)",
    calories: 143,
    carbohydrates: 0,
    protein: 27,
    fat: 3,
    fiber: 0,
    sugar: 0,
    sodium: 82,
  },
  {
    name: "Apel (mentah, dengan kulit)",
    calories: 52,
    carbohydrates: 14,
    protein: 0.3,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
  },
  {
    name: "Jeruk (mentah)",
    calories: 47,
    carbohydrates: 12,
    protein: 0.9,
    fat: 0.1,
    fiber: 2.4,
    sugar: 9,
    sodium: 0,
  },
  {
    name: "Pisang (mentah)",
    calories: 89,
    carbohydrates: 23,
    protein: 1.1,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    sodium: 1,
  },
  {
    name: "Air putih (mineral)",
    calories: 0,
    carbohydrates: 0,
    protein: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
  },
  {
    name: "Jus jeruk (tanpa gula tambahan)",
    calories: 45,
    carbohydrates: 10.4,
    protein: 0.7,
    fat: 0.2,
    fiber: 0.2,
    sugar: 8.4,
    sodium: 1,
  },
  {
    name: "Jus apel (tanpa gula tambahan)",
    calories: 46,
    carbohydrates: 11,
    protein: 0.1,
    fat: 0.1,
    fiber: 0.2,
    sugar: 9.6,
    sodium: 4,
  },
  {
    name: "Jus pisang (tanpa gula tambahan)",
    calories: 90,
    carbohydrates: 21,
    protein: 1.2,
    fat: 0.3,
    fiber: 1.8,
    sugar: 14,
    sodium: 2,
  },
];
